name: Deploy Plugin Release
on:
  release:
    types: [published]
jobs:
  wporg:
    name: Deploy Release to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - name: Fetch plugin zip from release
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          version: ${{ github.event.release.id }}
          file: wp-job-manager.zip
      - name: Decompress plugin
        run: unzip wp-job-manager.zip
      - name: Deploy to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          dry-run: true
        env:
          SVN_PASSWORD: ${{ secrets.WORDPRESSORG_SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.WORDPRESSORG_SVN_USERNAME }}
          BUILD_DIR: wp-job-manager
          SLUG: wp-job-manager
      - name: Comment
        run: gh pr comment $(gh pr list -s closed -S "Release ${{ github.event.release.tag_name }}" --json=number -q ".[0].number") --body "✅ Release ${{ github.event.release.tag_name }} deployed to WordPress.org"
        
  
  
