name: Deploy GitHub Pages

on:
  push:
    branches:
      - trunk
      - workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7.0.1
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@eff65dc3f193f0a749872be82f74baa35be0797d # v1.3.0
        with:
          output: swagger-ui
          spec-file: ./docs/api/internal.json
          version: "^4.18.0"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
          destination_dir: api/internal
